language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
notifications:
  email:
    recipients:
      - eduar.diaz37@gmail.com
      - davidsingal@icloud.com
      - josealvarez712@gmail.com