language: node_js
node_js:
  - 0.10
services:
  - mongodb
before_script:
  - npm install -g grunt-cli bower
  - bower install
notifications:
  email:
    recipients:
      - eduar.diaz37@gmail.com
      - davidsingal@icloud.com
      - josealvarez712@gmail.com